import smtplib
import pandas
from datetime import datetime as dt
today = dt.today()
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
attachments = []

def send_email():
    print("sending emails")
    df = pandas.read_csv('contacts.csv')
    for index, row in df.iterrows():
        msg = MIMEMultipart()
        msg["Subject"] = "Open Jobs on Indeed.com"
        msg["From"] = "noreply@etteplan.com"
        msg["To"] = row['email']

        # Add email body
        body = MIMEText(f"Hello {row['name']}, here's attached files gererated by AJS-application. \nEmail generated by Lauri Kyttälä")
        msg.attach(body)

        file1 = row['filepath1']
        file1_striped = file1.strip()
        print(f"file1_striped: {file1_striped}")

        file2 = row['filepath2']
        file2_striped = file2.strip()
        print(f"file2_striped: {file2_striped}")

        if file2_striped == "sorted.json":
            print(file2_striped)
        else:
            print("error with file giving")

if __name__ == '__main__':
    send_email()