import smtplib
import pandas
from datetime import datetime as dt
today = dt.today()
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import numpy as np


def send_email():
    attachments = []
    print("sending emails")
    df = pandas.read_csv('contacts.csv')
    for index, row in df.iterrows():
        msg = MIMEMultipart()
        msg["Subject"] = "Open Jobs on Indeed.com"
        msg["From"] = "noreply@etteplan.com"
        msg["To"] = row['email']

        # Add email body
        body = MIMEText(f"Hello {row['name']}, here's attached files gererated by AJS-application. \nEmail generated by Lauri Kyttälä")
        msg.attach(body)

        # file1 = row['filepath1']
        # print(type(file1))
        # print(type(row['filepath1']))

        file2 = row['filepath2']
        if file2 == "nan":
            print("error")
        print(f"file2 {file2}")
        print('*'*25)        
        print(row['filepath2'])
        print('*'*25)


if __name__ == '__main__':
    send_email()