import smtplib
import pandas
from datetime import datetime as dt
today = dt.today()
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import numpy as np


def send_email():
    attachments = []
    print("sending emails")
    df = pandas.read_csv('contacts.csv')
    for index, row in df.iterrows():
        msg = MIMEMultipart()
        msg["Subject"] = "Open Jobs on Indeed.com"
        msg["From"] = "noreply@etteplan.com"
        msg["To"] = row['email']

        # Add email body
        body = MIMEText(f"Hello {row['name']}, here's attached files gererated by AJS-application. \nEmail generated by Lauri Kyttälä")
        msg.attach(body)

        if row['filepath2'] == "sorted.json":
            print("The variable is sorted.json")
            attachments = [row['filepath1'], row['filepath2']]          
        else:
            print("The variable is NaN.")
            attachments = [row['filepath1']]

        print(attachments)

if __name__ == '__main__':
    send_email()