import smtplib
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication
import os
from dotenv import load_dotenv
load_dotenv()
token = os.environ.get("ETTEPLAN_PASS")

email_receiver = "lauri.kyttala@gmail.com"

msg = MIMEMultipart()
msg["Subject"] = "Open Jobs on Indeed.com"
msg["From"] = "noreply@etteplan.com"
msg["To"] = email_receiver

# Add email body
body = MIMEText("Hello, here's attached jobs.docx gererated by AJS-application. \nEmail generated by Lauri Kyttälä")
msg.attach(body)

# Add attachment
with open("jobs.docx", "rb") as file:
    attachment = MIMEApplication(file.read())
    attachment.add_header(
        "Content-Disposition", "attachment", filename="jobs.docx"
    )
msg.attach(attachment)

server = smtplib.SMTP("82.195.202.152", 25)  # Replace with the actual server address and port

server.send_message(msg)

server.quit()

print("Emails send!")
