import smtplib
import pandas
from datetime import datetime as dt
today = dt.today()
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.application import MIMEApplication

def send_email():
    print("send_email")
    # email_receiver = "lauri.kyttala@gmail.com"
    df = pandas.read_csv('contacts.csv')
    for index, row in df.iterrows():
        msg = MIMEMultipart()
        msg["Subject"] = "Open Jobs on Indeed.com"
        msg["From"] = "noreply@etteplan.com"
        msg["To"] = row['email']

        # Add email body
        body = MIMEText("Hello, here's attached jobs.docx gererated by AJS-application. \nEmail generated by Lauri Kyttälä")
        msg.attach(body)

        # Add attachment
        with open("jobs.docx", "rb") as file:
            attachment = MIMEApplication(file.read())
            attachment.add_header(
                "Content-Disposition", "attachment", filename="jobs.docx"
            )
        msg.attach(attachment)
        server = smtplib.SMTP("82.195.202.152", 25)  # Replace with the actual server address and port
        server.send_message(msg)
        server.quit()
        print(f"Email #{index} send!")

if __name__ == '__main__':
    send_email()